language: csharp
solution: GestaoEscolar.sln
install:
  - nuget restore GestaoEscolar.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release GestaoEscolar.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./GestaoEscolar.Domain.Test/bin/Release/GestaoEscolar.Domain.Test.Tests.dll
