sqlserver:
    image: microsoft/mssql-server-linux
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Mz28st8bnHUC8xW
rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /docker/rabbitmq/data:/var/lib/rabbitmq       
        
  
  
#SQL Server 
#Server=127.0.0.1,1433;
#Database=Master;
#User Id=SA;
#Password=Mz28st8bnHUC8xW