sqlserver:
    image: microsoft/mssql-server-linux
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=GuiGui@2016
rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /docker/rabbitmq/data:/var/lib/rabbitmq       